#!/bin/bash
set -eu

# Change this to the location where you installed the jar file.
JAR=$HOME/bin/lsd-__VERSION__.jar
HEAP_SIZE=-Xmx4G

CLASSPATH=$JAR:./
java $HEAP_SIZE -cp $CLASSPATH org.anc.lapps.dsl.LappsDsl "$@"


